第2回課題の感想記入しました。
tomoki-hamano-a/RaiseTech-portfolio pull request #1
Opened 2023-07-15 11:44 UTC by tomoki-hamano-a

#第2回課題できました。
##過去の録画授業見ながら順を追って課題取り組みました。時間がかかりましたが終えることができましたのでご連絡させていただきます。ご確認よろしくお願い致いたします。

2023-07-15 11:56 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-07-15 11:56 UTC, MasatoshiMizumoto commented on lecture02.md
> +授業スライドを見返しながら少しづつ慣れて行きます。
Markdownになっていないのと、見出しと本文は同じ使い方してはいけないので、書き分けていただきたいです！

2023-07-16 15:37 UTC, tomoki-hamano-a commented
# 第２回課題修正
- 修正できたので確認お願いいたします。

2023-07-16 16:12 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応お願いします！！

2023-07-16 16:12 UTC, MasatoshiMizumoto commented on lecture02.md
> +# 第2改課題感想
このままにしておいても大丈夫ですが直しておきましょうか！
```suggestion
# 第2回課題感想
```

2023-07-17 14:28 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-07-18 01:18 UTC, merged